// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiET75pNgi4ljpbrDTwUu4T9KIxhsBxo',
    appId: '1:171638354714:android:8e36b2e847ea45680872a3',
    messagingSenderId: '171638354714',
    projectId: 'cabai-bbf3f',
    authDomain: 'cabai-bbf3f.firebaseapp.com',
    databaseURL: 'https://cabai-bbf3f-default-rtdb.firebaseio.com/',
    storageBucket: 'cabai-bbf3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBiET75pNgi4ljpbrDTwUu4T9KIxhsBxo',
    appId: '1:171638354714:android:8e36b2e847ea45680872a3',
    messagingSenderId: '171638354714',
    projectId: 'cabai-bbf3f',
    databaseURL: 'https://cabai-bbf3f-default-rtdb.firebaseio.com/',
    storageBucket: 'cabai-bbf3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBiET75pNgi4ljpbrDTwUu4T9KIxhsBxo',
    appId: '1:171638354714:android:8e36b2e847ea45680872a3',
    messagingSenderId: '171638354714',
    projectId: 'cabai-bbf3f',
    databaseURL: 'https://cabai-bbf3f-default-rtdb.firebaseio.com/',
    storageBucket: 'cabai-bbf3f.appspot.com',
    iosClientId: '552095356879-11mh7k5odt3carunehiuvoe0vc9uva7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileTaCabaiku',
  );
}
